[package]
name = "rust_rhythm_windows"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rr_core = { path = "../." }
env_logger = "0.11.3"
log = "0.4.21"
